services:
  backend:
    image: anime-backend
    build:
       context: ./
       dockerfile: Dockerfile
    ports:
      - "8080:8080"

  frontend:
    image: anime-frontend
    build: ../Bingeworthy.anime
    ports:
      - "80:80"
    depends_on:
      - backend

networks:
  default:
    name: anime-network