services:

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI="mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@${MONGODB_CLUSTER}/${MONGODB_DATABASE}"
    env_file:
      - src/main/resources/.env

  frontend:
    build: ../Bingeworthy.anime
    ports:
      - "3000:3000"
    depends_on:
      - backend
