name: Backend CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      env:
        MONGODB_DATABASE_TEST: ${{ secrets.MONGODB_DATABASE_TEST }}
        MONGODB_USER: ${{ secrets.MONGODB_USER }}
        MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
        MONGODB_CLUSTER: ${{ secrets.MONGODB_CLUSTER }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        CORS_ALLOWED_ORIGINS: ${{ secrets.CORS_ALLOWED_ORIGINS }}
        G_API_KEY: ${{ secrets.G_API_KEY }}
      run: mvn clean package

    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Configure Docker
      run: gcloud auth configure-docker

    - name: Build and Push Docker image
      env:
        IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/anime-backend
      run: |
        docker build -t $IMAGE_NAME:${{ github.sha }} .
        docker push $IMAGE_NAME:${{ github.sha }}

    - name: Deploy to Cloud Run
      env:
        MONGODB_DATABASE: ${{ secrets.MONGODB_DATABASE }}
        MONGODB_USER: ${{ secrets.MONGODB_USER }}
        MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
        MONGODB_CLUSTER: ${{ secrets.MONGODB_CLUSTER }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        CORS_ALLOWED_ORIGINS: ${{ secrets.CORS_ALLOWED_ORIGINS }}
        G_API_KEY: ${{ secrets.G_API_KEY }}
      run: |
        gcloud run deploy backend-service \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/anime-backend:${{ github.sha }} \
          --platform managed \
          --region europe-west1 \
          --allow-unauthenticated \
          --set-env-vars MONGODB_DATABASE=${{ secrets.MONGODB_DATABASE }},MONGODB_USER=${{ secrets.MONGODB_USER }},MONGODB_PASSWORD=${{ secrets.MONGODB_PASSWORD }},MONGODB_CLUSTER=${{ secrets.MONGODB_CLUSTER }},SECRET_KEY=${{ secrets.SECRET_KEY }},CORS_ALLOWED_ORIGINS=${{ secrets.CORS_ALLOWED_ORIGINS }},G_API_KEY=${{ secrets.G_API_KEY }}